# _config.yml

# Site settings
title: μ•„μΌλλ“ κ²μ¤νΈν•μ°μ¤
description: >- # κ²€μƒ‰ κ²°κ³Όμ— λ³΄μΌ μ‚¬μ΄νΈ μ„¤λ…μ…λ‹λ‹¤.
  μ μ£Όλ„μ— μ„μΉν• μ•„λ‘ν•κ³  νΈμ•ν• μ•„μΌλλ“ κ²μ¤νΈν•μ°μ¤μ…λ‹λ‹¤.

# Build settings
baseurl: "" # π‘ μ‚¬μ©μ μ‚¬μ΄νΈ(nujabes.github.io)λ” λ°λ“μ‹ λΉ„μ›λ‘μ–΄μ•Ό ν•©λ‹λ‹¤.
url: "https://islandguesthouse.kr" # π‘ λ³ΈμΈμ μµμΆ… μ‚¬μ΄νΈ μ£Όμ†μ…λ‹λ‹¤.

# Exclude from processing
# μµμΆ… μ‚¬μ΄νΈμ— ν¬ν•¨λμ§€ μ•μ„ νμΌλ“¤μ…λ‹λ‹¤.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md